### ISSUE TITLE
Erkennen eines Lehrer Accounts auf Lanis

### ISSUE THREAD

**Issue by alessioc42** [marshei/sph-vertretungsplan#3]
Moin,
vor einiger Zeit habe ich begonnen eine Android App zu entwickeln, die genau wie Ihre Anwendung Benachrichtigungen des Vertretungsplans als Push-Benachrichtigung versendet. Mein Ziel war es, diese App ohne Server zum Laufen zu bringen. 
Im Laufe der Zeit wurde das Projekt um weitere Funktionen des SPH erweitert und wurde schließlich zu [Lanis Mobile](https://github.com/alessioC42/lanis-mobile). Die App wird voraussichtlich nach den Winterferien im Google Play Store verfügbar sein. 
Während es bei den SPH Anwendungen wie Vertretungsplan oder Kalender keine Probleme geben sollte, bin ich mir mehr als sicher, dass es spätestens bei "Mein Unterricht" Probleme wegen möglichen Lehreraccounts geben wird. 
Meine Frage wäre, ob Sie einen API-Endpoint kennen, mit dem man den Accounttyp sicher ermitteln kann?
LG

**Comment by marshei** [comment]
Die Frage kann ich leider nicht beantworten.

`ajax_login.php` antwortet mit einer 4-stelligen Zahl, deren Bedeutung unklar ist.

Die Seite `benutzerverwaltung.php?a=userData` gibt ja Stufe und Klasse an ... dies könnte ein Ansatz für die Unterscheidung sein.

**Comment by alessioc42** [comment]
Über den Userdata Ansatz habe ich auch nachgedacht. Gibt es ein Feld, dass nicht in Lehrer Accounts vorhanden ist? Bei mir existieren zumindest "Stufe" und "Klasse" als eigenes Feld. Ist das bei ihnen vorhanden? Dann könnte man mit der Abwesenheit dieser Felder arbeiten.

**Comment by marshei** [comment]
Ich habe hier nur einen Schüleraccount zur Verfügung. Beim Aufruf der Benutzerdaten werden folgende Felder angezeigt:

- Login
- Nachname
- Vorname
- Geburtsdatum
- Stufe
- Klasse
- Geschlecht

Ich habe vermutet, dass Stufe und/oder Klasse bei einem Lehreraccount nicht gesetzt sind.

Alternativ - sofern das Geburtsdatum gesetzt ist - könnte das Alter des Accountinhabers ja Auskunft geben ...

**Comment by alessioc42** [comment]
Oh, ich war mir irgendwie sicher, dass sie einen Lehreraccount haben. 
Ich werde mal bei meinem Tutor nachfragen. 
Danke für den Input.
